services:
  app:
    build: .
    environment:
      - PORT=4000
      - PHX_HOST=${PHX_HOST:?}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?}
      - TOKEN_SIGNING_SECRET=${TOKEN_SIGNING_SECRET:?}
      - DATABASE_URL=${DATABASE_URL:?}
      - SWOOSH_ADAPTER=${SWOOSH_ADAPTER:-Swoosh.Adapters.Local}
      - MAILER_API_KEY=${MAILER_API_KEY:-}
      - MAILER_DOMAIN=${MAILER_DOMAIN:-}
    command: sh -c "/app/bin/migrate && /app/bin/server"
    expose:
      - "4000"
    restart: always
